### PR TITLE
Added files for verifying [Policies] language of the message requested doesn't exist in LocalPT

### PR DESCRIPTION
**Pull request by aarotar**

### CODE REVIEW

**Comment by aarotar** [comment]
@vvvakulenko please review

**Comment by aarotar** [comment]
@aderiabin please review

**Comment by vvvakulenko** [comment]
@maria-mih Please review

**Comment by aarotar** [comment]
@maria-mih, please review

**Comment by istoimenova** [comment]
@LuxoftAKutsan  please merge.

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge.

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge.

**Pull request merged**
