### PR TITLE
Remove undefined info param from response validation

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
ATF Test Scripts to check #[2974]( https://github.com/smartdevicelink/sdl_core/issues/2974)

This PR is **[ready]** for review.

### Summary
According to HMI specification, result structure has no any messages and SDL doesn't resent any 'info' messages to the mobile, this is why I removed 'info' validation 

### ATF version
 https://github.com/smartdevicelink/sdl_atf/tree/develop(d6c2138)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by dboltovskyi** [comment]
I'm not sure this is correct fix
According to Mobile API there is an `info` attribute in response for `PerformInteraction`
I supposed SDL has to populate this attribute depends on response from HMI.

**Comment by dboltovskyi** [comment]
Another option is to transfer `info` from HMI response to Mobile
`info` shouldn't be in HMI API since this is technical `message` attribute

**Comment by LitvinenkoIra** [comment]
@dboltovskyi According to https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/blob/develop/docs/UI/PerformInteraction/index.md 
successful response from HMI shouldn't contain any 'info' attribute,
but erroneous response should contain  'message' attribute and in case of erroneous response with the 'message' SDL successfully resend this 'message' to the mobile in 'info' field (check PI_PerformViaBOTH function in scripts)

**Comment by dboltovskyi** [comment]
@LitvinenkoIra Please notice there is a req-t in [0042-transfer-invalid-image-rpc](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0042-transfer-invalid-image-rpc.md) regarding the case implemented in script
```
HMI -> SDL: RPC (WARNINGS, message: “Requested image(s) not found”)
SDL -> app: RPC (WARNINGS, info: “Requested image(s) not found)”)
```
It's need to be handled somehow.

**Comment by LitvinenkoIra** [comment]
@dboltovskyi please take a look at a5d31cd080b1d4cbde7c8ed5b5701f5fb18a0d0d
We can check the following reqs:
```
HMI -> SDL: RPC (WARNINGS, message: “Requested image(s) not found”)
SDL -> app: RPC (WARNINGS, info: “Requested image(s) not found)”)
```
only if the HMI responds with an error message, so I changed SendResponse to SendError to check forwarding 'info' and removed the undefined info parameter from the successful response check.

**Comment by dboltovskyi** [comment]
@LitvinenkoIra In commit you provided `choiceID` sent from HMI will be empty since this an error message type.
Though we're expecting this attribute on mobile side.

**Comment by LitvinenkoIra** [comment]
@dboltovskyi We are expecting choiceId on mobile side after this successful response https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2255/files#diff-bb3b5166223b1277d6c23630db08311cR188 

it's not possible to send the choiceId via erroneous response.

**Comment by dboltovskyi** [comment]
@LitvinenkoIra
I've pushed one update in 4ae69e9 
I think currently it's no possible to handle `MANUAL_ONLY` mode.

Reason:
There is an expectation to have `info` = `Requested image(s) not found` on mobile side.
SDL could only transfer this message from HMI.
However HMI is unable to send it since it has to provide `choiceID` attribute in `UI.PerformInteraction` response.  
HMI in this case has to choose between 2 options (if it follows guidelines):
1) To send erroneous response with `message` attribute populated, but without `choiceID`
2) To send success response without `message` attribute, but with `choiceID`

So initial requirement mentioned in [0042-transfer-invalid-image-rpc](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0042-transfer-invalid-image-rpc.md) couldn't be met in this particular case.

**Comment by dboltovskyi** [comment]
It was agreed with the team and proposal author to do the following:
1) Disable verification of `info` field in response for `MANUAL_ONLY` mode of `PerformInteraction`.
Since currently this can't be done due to HMI Guidelines restrictions
2) Create a new proposal to add possibility to transfer `message` attribute from `HMI` through `SDL` to `Mobile App` for `success` responses (as currently works for `erroneous` ones)

**Comment by dboltovskyi** [comment]
@theresalech Please consider this PR as a fix for https://github.com/smartdevicelink/sdl_core/issues/2974 which needs to be reviewed by PM.

**Pull request merged**
