### PR TITLE
Added files for verifying [Policies] SDL.ActivateApp from HMI, the device this app is running on is unconsented

### PR DESCRIPTION
**Pull request by aarotar**

### CODE REVIEW

**Comment by aarotar** [comment]
@vvvakulenko please review

**Comment by aarotar** [comment]
@aderiabin please review

**Comment by aarotar** [comment]
@vvvakulenko , @aderiabin please use last commit for review

**Comment by aarotar** [comment]
@maria-mih, please review

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge

**Pull request merged**
