### PR TITLE
Scripts for "Handle response from HMI during resumption data"

### PR DESCRIPTION
**Pull request by GetmanetsIrina**
#### Note: This PR should be merged BEFORE #2090 and #2138 as it is the basis for implementation and script creation of Interior Vehicle Data resumption and Button Subscription response from HMI

ATF Test Scripts to check #[2486](https://github.com/smartdevicelink/sdl_core/issues/2486)
This PR is **ready** for review.

### Summary
Script for "Handle response from HMI during resumption data"

### ATF version
[Develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by dboltovskyi** [comment]
Closed. New PR will be created with new source branch.

**Comment by yang1070** [comment]
@dboltovskyi  what is the new PR number with new source branch?

**Comment by dboltovskyi** [comment]
@yang1070 Please notice test scripts (as well as other deliverables) for this feature are going to be published for Ford team review at Aug-10

**Comment by yang1070** [comment]
@dboltovskyi thank you for the update. I will wait till 8/10 to start the review

**Comment by dboltovskyi** [comment]
Closed in a favor of https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2441

**Pull request closed without merging**
