### PR TITLE
Get list of permissions with appID

### PR DESCRIPTION
**Pull request by vvvakulenko**

### CODE REVIEW

**Comment by vvvakulenko** [comment]
@istoimenova please review

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge.

**Comment by LuxoftAKutsan** [comment]
@istoimenova this PR continst copnflicts unable to merge

**Comment by LuxoftAKutsan** [comment]
@istoimenova this PR contains conflicts. Unable to merge

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge.

**Pull request merged**
