### PR TITLE
Add test scripts and information how to run them

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**

### CODE REVIEW

**Comment by pestOO** [comment]
@LuxoftAKutsan, please split updatinf README and adding lua scripts

**Comment by LuxoftAKutsan** [comment]
@malirod @pestOO  please review

**Comment by pestOO** [comment]
@LuxoftAKutsan, Also it's will be more appropriate 
a) create 2 PRs - for readme update and for test update
b) splt Readme and lua sript files update in different commits
c) update description

**Comment by LuxoftAKutsan** [comment]
@pestOO  I don't agree with 2 PR. It is redundant bureaucracy 

Commits splited more clearly.

**Comment by LuxoftAKutsan** [comment]
@pestOO  please review

**Comment by malirod** [comment]
reviewed

**Comment by LuxoftAKutsan** [comment]
@pestOO please merge

**Comment by LuxoftAKutsan** [comment]
@pestOO Please DON't mwerge. We will test this flow.

**Comment by pestOO** [comment]
@LuxoftAKutsan, please ask @AGaliuzov or @anosach-luxoft for merging in all FORD opensource repositories.

**Pull request merged**
