### PR TITLE
Scripts for feature "LIGHT more name and status values"

### PR DESCRIPTION
**Pull request by GetmanetsIrina**
ATF Test Scripts to check #[2172](https://github.com/smartdevicelink/sdl_core/issues/2172)

This PR is **ready** for review.

### Summary
Scripts for feature "Remote Control – Lights – More Names and Status Values" 

### ATF version
[Develop branch](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### CODE REVIEW

**Comment by yang1070** [comment]
when I run the test scripts, there are a lot of 
`OnPermissionsChange notification: Timeout: OnPermissionsChange notification: Timeout expired` messages, and an example is in the following

```xml
==============================
Start 'test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/019_Light_more_values_READ_ONLY_in_case_statusAvailable_false.lua'
==============================
 WARNING: Parameter pathToSDLInterfaces is not specified, default APIs are used 
SDL build option EXTENDED_POLICY is unavailable.
Assume that SDL was built with EXTENDED_POLICY = PROPRIETARY
SDL build option REMOTE_CONTROL is unavailable.
Assume that SDL was built with REMOTE_CONTROL = ON
=====================================================================================================
Description: ATF test script
Severity: Major
=====================================================================================================
--- Preconditions -----------------------------------------------------------------------------------
[14:13:08,071] Clean_environment                                                                     [SUCCESS] (0 ms)
SDL pid 12754
tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN     
HMI initialized
HMI is ready
Mobile connected
[14:13:09,105] Start_SDL__HMI__connect_Mobile__start_Session                                         [SUCCESS] (708 ms)
App 1 was used for PTU
[14:13:09,887] RAI__PTU                                                                              [FAIL] (11086 ms)
 OnPermissionsChange notification: Timeout: OnPermissionsChange notification: Timeout expired
[14:13:21,034] Activate_App                                                                          [SUCCESS] (38 ms)
--- Test --------------------------------------------------------------------------------------------
[14:13:21,074] SetInteriorVehicleData_READ_ONLY                                                      [SUCCESS] (1902 ms)
--- Postconditions ----------------------------------------------------------------------------------
[14:13:22,980] Stop_SDL                                                                              [SUCCESS] (1 ms)
Total executing time is 17s 94ms (summary 17094ms)
==============================
Finish 'test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/SetInteriorVehicleData/019_Light_more_values_READ_ONLY_in_case_statusAvailable_false.lua'
```

Please take a look, thanks

**Comment by GetmanetsIrina** [comment]
@yang1070 , It is look like you run ATF scripts with updated sdl_preloaded_pt.json.
SDL already has permissions that ATF tries to set for it, and because the permissions are not updated to new ones SDL does not sends OnPermissionsChange notification and script got timeout on mobile side.

Please restore sdl_preloaded_pt.json to initial state and try again.

**Comment by GetmanetsIrina** [comment]
Fixed issue with `UNSUPPORTED_RESOURCE` resultCode in case `statusAvailable = false`.

**Comment by GetmanetsIrina** [comment]
Added changes in script regarding changes in code, added one more case for checking UNSUPPORTED_RESOURCE in case light value is not present in capabilities.

**Comment by yang1070** [comment]
@theresalech Ford approves this PR.

**Comment by JackLivio** [comment]
I am receiving this error on the first test script for light status
```
==============================
Start './test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetSystemCapability/001_Success_flow.lua'
==============================
=====================================================================================================
Description: ATF test script
Severity: Major
=====================================================================================================
--- Preconditions -----------------------------------------------------------------------------------
[12:27:25,326] Backup_HMI_capabilities_file                                                          [SUCCESS] (335 ms)
[12:27:25,665] Update_HMI_capabilities_file                                                          [SUCCESS] (216 ms)
[12:27:26,065] Clean_environment                                                                     [SUCCESS] (2 ms)
SDL pid 22475
tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN     
HMI initialized
HMI is ready
Mobile connected
[12:27:27,091] Start_SDL__HMI__connect_Mobile__start_Session                                         [SUCCESS] (766 ms)
App 1 was used for PTU
[12:27:27,887] RAI__PTU                                                                              [SUCCESS] (2426 ms)
[12:27:30,321] Activate_App                                                                          [SUCCESS] (34 ms)
--- Test --------------------------------------------------------------------------------------------
[12:27:30,366] GetSystemCapability_Positive_Case                                                     [FAIL] (144 ms)
 Response to 4: ValidIf: 
type of data payload.systemCapability.remoteControlCapability.climateControlCapabilities.1.currentTemperatureAvailable: expected boolean, actual type: nil
--- Postconditions ----------------------------------------------------------------------------------
[12:27:30,519] Stop_SDL                                                                              [SUCCESS] (3 ms)
[12:27:34,549] Restore_HMI_capabilities_file                                                         [SUCCESS] (1 ms)
Total executing time is 9s 320ms (summary 9320ms)

```

**Comment by GetmanetsIrina** [comment]
@JackLivio, there is the issue on develop regarding currentTemperatureAvailable - https://github.com/smartdevicelink/sdl_core/issues/2523 .
So this failr is related to currentTemperatureAvailable issue.

**Comment by GetmanetsIrina** [comment]
Scripts are rebased on https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1973 .

**Pull request merged**
