### PR TITLE
Feature/sdl 0264 separating the change of audible status and the change of hmi status

### PR DESCRIPTION
**Pull request by Yuki-Kanadome-Nexty**
ATF Test Scripts to check [#3227](https://github.com/smartdevicelink/sdl_core/issues/3227)

This PR is [ready] for review.

### Summary
modified for sdl 0264 separating the change of audible status and the change of hmi status

### ATF version
develop

### Changelog
- Updated 020_different_types_apps_interactions.lua
- Updated smoke/020_different_types_apps_interactions.lua

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by Yuki-Kanadome-Nexty** [comment]
@JackLivio -san
This PR is ready review.
Thank you!

**Review by jacobkeeler — CHANGES_REQUESTED** [review]
Other tests that are failing with these Core changes:

- test_scripts/API/SubtleAlertStyle/SubtleAlert/008_Phone_Call_Active_REJECTED.lua
- test_scripts/WebEngine/WebEngineProjection/014_HMI_status_transitions_different_applications_interactions.lua

Looks like the fixes are fairly similar

**Comment by jordynmackool** [comment]
@Yuki-Kanadome-Nexty please see Jacob's feedback above and let us know if you have any questions.

**Comment by jordynmackool** [comment]
Hi @Yuki-Kanadome-Nexty, to ensure we stay on track for the planned October 27, 2021 release, please respond/update this PR based on the feedback provided by Jacob as soon as possible. Thanks!

**Comment by jacobkeeler** [comment]
@Akihiro-Miyazaki https://github.com/smartdevicelink/sdl_core/pull/3738 has been approved as a note, please let us know if you need anything from us in order to update this PR (or create a new one) with the changes requested in [this comment](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2524#pullrequestreview-691177843).

**Comment by Akihiro-Miyazaki** [comment]
@jacobkeeler -san,
Sorry for late response.

> * test_scripts/WebEngine/WebEngineProjection/014_HMI_status_transitions_different_applications_interactions.lua

We will modify the 014_HMI_status_transitions_different_applications_interactions.lua as below such as 020_different_types_apps_interactions.lua file.
`
    [5] = {
      action = { event = common.userActions.phoneCallStart, appId = "none" },
      checks = {
        onHmiStatus = {
-         [1] = { hmiLvl = "BACKGROUND", audio = "NOT_AUDIBLE", video = "NOT_STREAMABLE" },
+         [1] = { hmiLvl = "LIMITED", audio = "NOT_AUDIBLE", video = "NOT_STREAMABLE" },
          [2] = { }, -- hmiLvl = "BACKGROUND", audio = "NOT_AUDIBLE", video = "NOT_STREAMABLE"
          [3] = { }, -- hmiLvl = "BACKGROUND", audio = "NOT_AUDIBLE", video = "NOT_STREAMABLE"
-         [4] = { hmiLvl = "LIMITED", audio = "NOT_AUDIBLE", video = "STREAMABLE" }
+         [4] = { hmiLvl = "FULL", audio = "NOT_AUDIBLE", video = "STREAMABLE" }
        }
      }
    },
`
If our change is wrong, could you please teach us.

> * test_scripts/API/SubtleAlertStyle/SubtleAlert/008_Phone_Call_Active_REJECTED.lua

In this matter, we have no solution how to change the file.
If you have a solution, could you please teach us.
Thank you.

**Comment by jacobkeeler** [comment]
@Akihiro-Miyazaki For `008_Phone_Call_Active_REJECTED.lua` you should just need to change the following lines in the `subtleAlertRejectedPhoneCall` function inside of `test_scripts/API/SubtleAlertStyle/commonSubtleAlert.lua`
```
  common.getMobileSession():ExpectNotification("OnHMIStatus",
-   { systemContext = "MAIN", hmiLevel = "LIMITED", audioStreamingState = "NOT_AUDIBLE" },
+   { systemContext = "MAIN", hmiLevel = "FULL", audioStreamingState = "NOT_AUDIBLE" },
    { systemContext = "MAIN", hmiLevel = "FULL", audioStreamingState = "AUDIBLE" })
  :Times(2)
```

**Review by jacobkeeler — DISMISSED** [review]

**Comment by jacobkeeler** [comment]
Closing in favor of #2567

**Pull request closed without merging**
