### PR TITLE
Script to check issue 2428

### PR DESCRIPTION
**Pull request by mkorniichuk**
ATF Test Scripts to check [#2428](https://github.com/SmartDeviceLink/sdl_core/issues/2428) [#1829](https://github.com/SmartDeviceLink/sdl_core/issues/1829)

This PR is **not ready** for review.
This is **draft** version of the script.

### Summary
A test script to verify that issue is fixed

### Notes:
Script succeeded only at SDL which is built with `CMAKE_BUILD_TYPE=Release`

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by dboltovskyi** [comment]
Livio team please do not review this PR for now since it hasn't passed our internal review yet.  
Review and appropriate updates going be done till 1st of November.
Thank you.

**Comment by IGapchuk** [comment]
The PR is rebased on the current develop branch (273b79d4d9bd2bd55bb728cc77effaf09004e443).
Script is applicable for all policy flows and transport types.
The script has been moved to 6_1 folder.
Test set for the script is added.

**Comment by dboltovskyi** [comment]
Script is updated to be included into 7.0 Release. However successful result can be received only at `Release` build type.

**Comment by GetmanetsIrina** [comment]
The successful result can be still received only at Release build type. Checked on https://github.com/smartdevicelink/sdl_core/tree/release/7.1.0-RC1 (c163c2d)

**Comment by GetmanetsIrina** [comment]
PR is closed because the test is passed on SDL build in the `Release` mode. There is no need to support the current SDL behaviour for the `Debug` mode.

**Pull request closed without merging**
