### PR TITLE
Created test script for case if one of RequestType parameters is invalid

### PR DESCRIPTION
**Pull request by aderiabin**
[Policies] PreloadPT one invalid and other valid values in "RequestType" array
@maria-mih please review my pull request

### CODE REVIEW

**Comment by aderiabin** [comment]
Script was updated according with test case template

@istoimenova please review my pull request

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge.

**Comment by istoimenova** [comment]
Clarification is waiting.

**Comment by dboltovskyi** [comment]
Moved to https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1061

**Pull request closed without merging**
