### PR TITLE
[SDL 0255] Feature/Enhance BodyInformation vehicle data

### PR DESCRIPTION
**Pull request by dboltovskyi**
ATF Test Scripts to check [#3133](https://github.com/smartdevicelink/sdl_core/issues/3133)

This PR is **[ready]** for review.

### Summary
Updates for Vehicle Data scripts related to "[SDL 0255] Enhance BodyInformation vehicle data" feature

### ATF version
[7.1.0_version_bump](https://github.com/smartdevicelink/sdl_atf/pull/217)

### Changelog
 - updated common module for RGNSD tests with new parameters

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@atiwari9 please review this PR

**Comment by atiwari9** [comment]
@dboltovskyi  - Can you please rebase with `feature/extended_vd_coverage`

**Comment by dboltovskyi** [comment]
@atiwari9 Please find update in 3e2f589

**Comment by atiwari9** [comment]
@dboltovskyi  - Some tests failed for `bodyInformation`, please see the logs: 
[BodyInfo_3Failed.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5637373/BodyInfo_3Failed.zip)

**Comment by dboltovskyi** [comment]
@atiwari9 It looks like environment issue.
All fails are related to `Start_SDL__HMI__connect_Mobile__start_Session` step and have `Error: Socket not opened` error message.

Could you do the following please:
1. Check there is no Web-HMI opened (e.g. in some browser tab). If so some of the messages from SDL could be processed not by ATF, but Web-HMI since the connection port is the same.
2. Restart these tests one more time.

**Comment by atiwari9** [comment]
Another run was successful : 
[BodyInfo_AllPass.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5654306/BodyInfo_AllPass.zip)

**Review by atiwari9 — APPROVED** [review]
Approved

**Comment by LitvinenkoIra** [comment]
@JackLivio This PR is ready for Livio review. Thank you!

**Review by iCollin — APPROVED** [review]

**Comment by iCollin** [comment]
Hello, would it be difficult to rebase this PR on develop? If it is not much effort, I would like to merge this PR before `feature/extended_vd_coverage`. Thank you!

**Comment by dboltovskyi** [comment]
@iCollin Please notice this PR has been re-based onto latest develop. However it couldn't be done without force-push.

**Review by iCollin — APPROVED** [review]

**Pull request merged**
