### PR TITLE
Scripts to check issue 2437

### PR DESCRIPTION
**Pull request by HSavynetska**
ATF Test Scripts to check [#2437](https://github.com/smartdevicelink/sdl_core/issues/2437)

This PR is **ready** for review.

### Summary
A test script to verify that issue is fixed

### ATF version
[develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### CLA
- [x ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by JackLivio** [comment]
@HSavynetska This test is marked as passing but the message core is sending to the mobile device is wrong.

```
SDL->MOB (19 10 2018 10:21:17, 494) [rpcFunction: OnVehicleData, sessionId: 1, version: 3, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 12, binaryDataSize: 0] : {"fuelLevel":-6,"fuelLevel_State":"UNKNOWN","speed":0,"rpm":0,"driverBraking":"NO_EVENT"} 
```

**Comment by dboltovskyi** [comment]
Livio team please do not review this PR for now since it hasn't passed our internal review yet.  
Review and appropriate updates going be done till 1st of November.
Thank you.

**Comment by dboltovskyi** [comment]
@JackLivio 
Script was updated a little (re-based onto current develop + cosmetic changes)
However result is the same on a current [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)

Please notice the following:
1. Issue is created against EXTERNAL_PROPRIETARY flow (there are user consents). Therefore script has to be run on appropriate SDL build.
2. In result you mentioned there are only allowed parameters: `fuelLevel`, `fuelLevel_State`, `speed`, `rpm` and `driverBraking`
And there are no not allowed ones: `instantFuelConsumption` and `externalTemperature`

So the result is correct

**Comment by jacobkeeler** [comment]
Issue is covered by existing vehicle data tests:
```
test_scripts/API/VehicleData/OnVehicleData/002_OnVD_disallowed.lua
test_scripts/API/VehicleData/OnVehicleData/003_OnVD_disallowed_after_PTU.lua
```

closing

**Comment by GetmanetsIrina** [comment]
@jacobkeeler, the script from current PR covers not the same case as 002_OnVD_disallowed.lua, 003_OnVD_disallowed_after_PTU.lua .
This script covers a specific case when OnVehicleData notification has the allowed and disallowed params so in this case notification should be forwarded to the mobile app by SDL.
002_OnVD_disallowed.lua, 003_OnVD_disallowed_after_PTU.lua cover case when the notification contains only disallowed params and notification should not be forwarded by SDL.
So I propose to reopen this PR and link it to the open issue https://github.com/smartdevicelink/sdl_core/issues/3365 .

**Pull request closed without merging**
