### PR TITLE
[SDL 0269] Feature/New vehicle data ClimateData

### PR DESCRIPTION
**Pull request by dboltovskyi**
ATF Test Scripts to check [#3198](https://github.com/smartdevicelink/sdl_core/issues/3198)

This PR is **[ready]** for review.

### Summary
Updates for Vehicle Data scripts related to "[SDL 0269] New vehicle data ClimateData" feature

### ATF version
[7.1.0_version_bump](https://github.com/smartdevicelink/sdl_atf/pull/217)

### Changelog
 - updated common modules for VD and RGNSD tests with new parameters

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@atiwari9 please review this PR

**Comment by atiwari9** [comment]
@dboltovskyi - Can you please rebase with `feature/extended_vd_coverage`

**Comment by dboltovskyi** [comment]
@atiwari9 Please find update in 94ed2ae

**Comment by atiwari9** [comment]
All tests specific to `climateData` passed: 
[ClimateData_AllPass.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5654332/ClimateData_AllPass.zip)

**Review by atiwari9 — APPROVED** [review]
Approved

**Comment by LitvinenkoIra** [comment]
@JackLivio This PR is ready for Livio review. Thank you!

**Review by ShobhitAd — APPROVED** [review]

**Comment by ShobhitAd** [comment]
@dboltovskyi  Please resolve merge conflicts

**Comment by dboltovskyi** [comment]
@ShobhitAd Please find conflicts resolved in 8e686d1

**Comment by ShobhitAd** [comment]
@dboltovskyi Some GenericNetworkData tests seem to be failing for `climateData`
Checking the atf logs for `002_GetVehicleData_with_PTU_with_VDitems.lua`  I see this response for `climateData`

```
===== GetVehicleData_climateData : 
MOB->SDL [09-02-2021 14:06:01,120] [rpcFunction: GetVehicleData, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 43, binaryDataSize: 0] : {"climateData":true} 

SDL->HMI [09-02-2021 14:06:01,124] {"id":69,"jsonrpc":"2.0","method":"VehicleInfo.GetVehicleData","params":{"climateData":true}}

HMI->SDL [09-02-2021 14:06:01,124] {"result":{"method":"VehicleInfo.GetVehicleData","code":0,"resultCode":"SUCCESS","success":true,"climateData":{"externalTemperature":{},"cabinTemperature":{},"atmosphericPressure":1024}},"id":69,"jsonrpc":"2.0"}

SDL->MOB [09-02-2021 14:06:01,135] [rpcFunction: GetVehicleData, sessionId: 1, version: 2, frameType: 1, encryption: false, serviceType: 7, frameInfo: 0, messageId: 49, binaryDataSize: 0] : {"resultCode":"GENERIC_ERROR","info":"Invalid message received from vehicle","success":false}  
```

**Comment by dboltovskyi** [comment]
@ShobhitAd Please find update in 9bfe03c

**Review by ShobhitAd — APPROVED** [review]

**Pull request merged**
