### PR TITLE
Updated common file to the #1714 issue

### PR DESCRIPTION
**Pull request by HSavynetska**
ATF Test Scripts to check #[1714](https://github.com/smartdevicelink/sdl_core/issues/1714)

This PR is **not ready** for review.

### Summary
Updated common file to the #1714 issue

### ATF version
develop

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by GetmanetsIrina** [comment]
@HSavynetska, please perform an update also in https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/6f43bfd3eba059a82db5f3ee2a3e00d3e1f5efbb/test_scripts/API/System/OnSystemRequest/001_OnSystemRequest_send_binaryData_for_any_requestType.lua#L63 for this issue, because there is no error message in case of failure.

**Comment by HSavynetska** [comment]
@GetmanetsIrina You can find the updates in the commit 0960c99

**Comment by GetmanetsIrina** [comment]
Script is rebased on actual develop(a7db5cc) branch.
Small update is performed.

**Comment by iCollin** [comment]
@dboltovskyi is this test still applicable? It seems that in late 2018 we just [added OEM_SPECIFIC to have binary data](https://github.com/smartdevicelink/sdl_core/commit/35c341bb1de8063ce0444513e2bcf14feeeb013c).

I am trying to determine if https://github.com/smartdevicelink/sdl_core/issues/1714 is still valid.

**Comment by dboltovskyi** [comment]
@iCollin 
I'm not sure if the issue is still applicable. If so script needs to be completely reworked using the latest common modules.

According to original https://github.com/smartdevicelink/sdl_core/issues/1714 issue SDL should be able to send binary data within any request type.
However this issue has been created before the implementation of [SDL-0083 Expandable design for proprietary data exchange](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0083-Expandable-design-for-proprietary-data-exchange.md) proposal and https://github.com/smartdevicelink/sdl_core/issues/2716 fix.

I would think it's better to ask the author of the issue and of the proposal.

@robinmk Could you comment please whether https://github.com/smartdevicelink/sdl_core/issues/1714 is still applicable?

**Comment by robinmk** [comment]
@dboltovskyi  It is still applicable.

**Comment by iCollin** [comment]
@dboltovskyi @robinmk Thank you for your help.

Closed in favor of https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2484

**Pull request closed without merging**
