### PR TITLE
015 Script for requirement [GeneralResultCodes] INVALID_DATA wrong characters - PerformAudioPassThru

### PR DESCRIPTION
**Pull request by maria-mih**
015_ATF_N_PerformAudioPassThru_INVALID_DATA_All_Params_audioPassThruIcon_DYNAMIC.lua 

Testing coverage available at #643
All common functions used available at #703
@istoimenova Please review

### CODE REVIEW

**Comment by istoimenova** [comment]
@maria-mih, please update script according to clarification: "Clarification about expected resut code when invalid <audioPassThruIcon> is sent"
@maria-mih, please reference the script in TestSet.

**Comment by maria-mih** [comment]
Script needs to be updated and renamed due to clarification of expected result when invalid parameter received.

**Comment by maria-mih** [comment]
@istoimenova 
Script is renamed and updated from 
015_ATF_P_PerformAudioPassThru_WARNINGS_All_Params_audioPassThruIcon_invalid_whitespaces_DYNAMIC.lua
to
015_ATF_P_PerformAudioPassThru_INVALID_DATA_All_Params_audioPassThruIcon_whitespaces_DYNAMIC
Please review it on commit c8ecc9bba55bdfe5666efd56a48f80685e7f3a33

**Comment by maria-mih** [comment]
Script is to be reworked to cover several possible scenarios with different preconditions but one expected result when request sent for all parameters and image type DYNAMIC and value parameter in image structure is invalid.
It will also be included as negative check of requirement [PerformAudioPassThru] SDL must transfer request to HMI in case of valid "audioPassThruIcon" param

**Comment by maria-mih** [comment]
@istoimenova Please note that script is renamed from 015_ATF_N_PerformAudioPassThru_INVALID_DATA_All_Params_audioPassThruIcon_DYNAMIC.lua 
to 
015_ATF_P_PerformAudioPassThru_INVALID_DATA_All_Params_audioPassThruIcon_whitespaces_DYNAMIC.lua 
Logic is changed so that all checks for invalid value parameter are included when mandatory parameters of request tested and imagetype = DYNAMIC
Available at commit b8ecc2f2700aeae53a6d3013162ed9de22a16381

**Pull request merged**
