### PR TITLE
Feature/rpc message protection

### PR DESCRIPTION
**Pull request by mked-luxoft**
ATF Test Scripts to check https://github.com/smartdevicelink/sdl_core/issues/2816

This PR is **ready** for review.
### Summary

Scripts for "[SDL 0207] - RPC message protection" feature
### ATF version
[develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### Manual checklist with screenshots
[Manual_instruction_for_RPC_message_protection.xlsx](https://github.ford.com/SmartDeviceLinkMirror/sdl_atf_test_scripts/files/9439/Manual_instruction_for_RPC_message_protection.xlsx)

### CLA
* [x]  I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by mked-luxoft** [comment]
@mrapitis please approve these pr, or feel free to suggest changes if necessary

**Comment by theresalech** [comment]
@mrapitis can you please advise if this is approved by Ford as well?

**Comment by mrapitis** [comment]
@theresalech Yes, Ford has approved of these changes.

**Comment by JackLivio** [comment]
@mked-luxoft @mrapitis I am seeing a lot of failures. Can you please confirm your atf tests are all passing?

**Comment by dboltovskyi** [comment]
@JackLivio Having SDL build from https://github.com/smartdevicelink/sdl_core/pull/2951 (`f87bb9a`), ATF https://github.com/smartdevicelink/sdl_atf/tree/develop (`ba1194b`) and test scripts from current PR we can confirm all tests are PASSED on `PROPRIETARY` and `EXTERNAL_PROPRIETARY` flows of SDL.
Could you provide more details on fails in order we can investigate them? (SDL and ATF logs). May be there is a dependency on environment.

**Comment by JackLivio** [comment]
Thank you! Re-running with develop.

**Comment by JackLivio** [comment]
`021_Unprot_Mode_Unprot_RPC_EncryptedNotRequired_PTU_IGN_OFF_ON_Unprot_Mode_Unprot_RPC_EncryptedRequired.lua`

Fails consistently for me. I think this is a common issue seen with other tests that start and stop core repeatedly. Have you ever experienced this before?

```
--- TC[005] -----------------------------------------------------------------------------------------
--- Preconditions -----------------------------------------------------------------------------------
kill: (7402): No such process
Doing .
[11:29:35,031] Clean_environment                                                                     [SUCCESS] (2 ms)
[11:29:36,777] Preloaded_update                                                                      [SUCCESS] (2 ms)
SDL pid 7430
tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN     
[11:29:37,339] Start_SDL__init_HMI                                                                   [FAIL] (10913 ms)
 HMI initialization: Timeout: HMI initialization: Timeout expired
[11:29:48,695] Register_App                                                                          [FAIL] (10400 ms)
 StartService ACK: Timeout: StartService ACK: Timeout expired
[11:29:59,601] Activate_App                                                                          [FAIL] (10711 ms)
 OnHMIStatus notification: Timeout: OnHMIStatus notification: Timeout expired
[11:30:10,805] Unprotected_RPC_in_unprotected_mode__Encrypted_not_required                           [FAIL] (10895 ms)
 HMI call UI.AddCommand: Timeout: HMI call UI.AddCommand: Timeout expired
 Response to 2: Timeout: Response to 2: Timeout expired
 OnHashChange notification: Timeout: OnHashChange notification: Timeout expired
[11:30:22,017] Register_App_2                                                                        [FAIL] (10692 ms)
 StartService ACK: Timeout: StartService ACK: Timeout expired
[11:30:33,221] Policy_Table_Update                                                                   [FAIL] (11162 ms)
 HMI call VehicleInfo.GetVehicleData: Timeout: HMI call VehicleInfo.GetVehicleData: Timeout expired
 PTU event: Timeout: PTU event: Timeout expired
[11:30:44,812] Unprotected_RPC_in_unprotected_mode                                                   [FAIL] (10897 ms)
 Response to 3: Timeout: Response to 3: Timeout expired
--- Test --------------------------------------------------------------------------------------------
SDL was shutdown successfully
[11:30:56,009] IGNITION_OFF                                                                          [SUCCESS] (2345 ms)
QIODevice::read: device not open
SDL pid 8117
tcp        0      0 127.0.0.1:8087          0.0.0.0:*               LISTEN     
[11:30:58,752] IGNITION_ON                                                                           [FAIL] (11585 ms)
 HMI initialization: Timeout: HMI initialization: Timeout expired
[11:31:10,789] Register_App                                                                          [FAIL] (10385 ms)
 StartService ACK: Timeout: StartService ACK: Timeout expired
[11:31:21,703] Activate_App                                                                          [FAIL] (10675 ms)
 OnHMIStatus notification: Timeout: OnHMIStatus notification: Timeout expired
[11:31:32,901] Unprotected_RPC_in_unprotected_mode                                                   [FAIL] (10878 ms)
 Response to 2: Timeout: Response to 2: Timeout expired
--- Postconditions ----------------------------------------------------------------------------------
PANIC: unprotected error in call to Lua API (./modules/services/control_service.lua:164: StartServiceAck was not received. Unable to stop not started service)

```

**Comment by JackLivio** [comment]
Also could you please break up some of the longer test scripts? 81 test cases is way to many for a single script eg 023 &024

**Comment by dboltovskyi** [comment]
@JackLivio As could be seen from this console log SDL was unable to start.
It could happen if another instance is running.
There are a few test cases in one script. There `005` in this part of log. Were previous ones 001 - 004 successful?
Every case has `postconditions` step which invokes `StopSDL()` function
And it seems this function was not successful due to `kill: (7402): No such process` message

**Comment by dboltovskyi** [comment]
@JackLivio Yes scripts with a lot of test cases could be split into a few ones

**Comment by JackLivio** [comment]
> There are a few test cases in one script. There 005 in this part of log. Were previous ones 001 - 004 successful?

Yes they were successful. It seems to fail by the time it gets to 005 pretty consistently.

**Comment by JackLivio** [comment]
Full console logs [atf_console.log.txt](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/3331630/atf_console.log.txt)

**Comment by dboltovskyi** [comment]
@JackLivio 
We did 5 runs in row of `021` script and they were successful. It seems you have strange environment issue.
I did additional investigation.
In script in each test case SDL is going to be killed 2 times: in `preconditions()` and in `postconditions()` functions.
However they used 2 different functions to do this (correspondingly):
- StopSDL() from `modules/SDL.lua`
- SDLForceStop() from `user_modules/shared_testcases/commonFunctions.lua

Message `kill: (7402): No such process` is related `SDLForceStop()` function.
It has the following code:
```
ps aux | grep ./smartDeviceLinkCore | awk '{print $2}' | xargs kill -9
```
So `ps` command shown that `smartDeviceLinkCore` process exists => pid 7402
However `kill` couldn't find it

Is `smartDeviceLinkCore` binaries have the same user permissions as ATF?
Is there any other processes on the same host which could run `smartDeviceLinkCore` process at the same time? (docker containers etc.)

**Comment by dboltovskyi** [comment]
Investigating the log there is `kill: (31398): No such process` message on every step
However we don't have such one at our environment

**Comment by dboltovskyi** [comment]
Scripts were failed due to performance degradation in ATF.
New issue is raised: https://github.com/smartdevicelink/sdl_atf/issues/169
Though, there is a workaround to switch ATF Report off by setting `config.excludeReport = true`

**Comment by dboltovskyi** [comment]
@JackLivio Scripts with many test cases `023` - `025` has been split into a few ones (each has ~20 test cases)

**Comment by dboltovskyi** [comment]
@JackLivio please approve this PR, or feel free to suggest changes if necessary

**Comment by mrapitis** [comment]
@theresalech Ford has approved of these changes.

**Comment by dboltovskyi** [comment]
Please notice PR has been re-based onto HEAD of develop

**Pull request merged**
