### PR TITLE
Scripts to check issue 2405

### PR DESCRIPTION
**Pull request by dboltovskyi**
ATF Test Scripts to check [#2405](https://github.com/smartdevicelink/sdl_core/issues/2405)

This PR is **ready** for review.

### Summary
A set of test scripts to verify that issue is fixed

### ATF version
[develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### CLA
- [x ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by conlain-k** [comment]
It seems like these scripts only test `GetVehicleData` with one parameter, `speed`. They should probably include other cases, such as a functional group allowing any parameters e.g. the Send `GetVehicleData("rpm")` case listed in https://github.com/smartdevicelink/sdl_core/issues/2405.

**Comment by dboltovskyi** [comment]
@conlain-k 
Actually issue [#2405](https://github.com/smartdevicelink/sdl_core/issues/2405) describes 2 cases:
1. FuncGroup1(EMPTY_ARRAY) + FuncGroup2(parameter)
2. FuncGroup1(EMPTY_ARRAY) + FuncGroup2(OMITTED)

There are following combinations for these 2 cases: 

|TC|Group1|Group2|Result|
-|-|-|-
|1|OMITTED|OMITTED|SUCCESS|
|2|OMITTED|EMPTY_ARRAY|SUCCESS|
|3|OMITTED|parameter|SUCCESS|
|4|EMPTY_ARRAY|OMITTED|SUCCESS|
|5|EMPTY_ARRAY|EMPTY_ARRAY|USER_DISALLOWED|
|6|EMPTY_ARRAY|parameter|SUCCESS|
|7|parameter|OMITTED|SUCCESS|
|8|parameter|EMPTY_ARRAY|SUCCESS|
|9|parameter|parameter|SUCCESS|

TC corresponds to test script number in this PR

There is do difference if use "speed" or "rpm" parameter - they are all equivalent. 

Please notice scripts were renamed and PR was re-based onto a HEAD of develop.

**Comment by conlain-k** [comment]
Hello @dboltovskyi, what I meant is that the scripts only test one parameter at a time. I believe there are more test cases, such as trying to get a parameter not explicitly allowed, but allowed via an omitted parameter set. 

I do not believe any of these tests would have caught the logic issue listed here: https://github.com/smartdevicelink/sdl_core/pull/2406#issuecomment-410011103, which is the second test case listed in the original issue https://github.com/smartdevicelink/sdl_core/issues/2405.

**Comment by dboltovskyi** [comment]
Hi @conlain-k 
Thank you for the explanation. I finally got your point.
I've put an additional parameter to all scripts.
Script `007` reveals an issue that you mentioned on https://github.com/AKalinich-Luxoft/sdl_core/commit/c71899ecf9d1be292646b80704a91fea97bb18d3 and shows this issue is fixed in https://github.com/AKalinich-Luxoft/sdl_core/commit/80291097033c8a6cd44a95f2ff4ff4def57e5e8e

Please find an updates in scripts in 7f5016c and 5500d4e

**Pull request merged**
