### PR TITLE
Add .json used in tests ATF_GetListOfPermissions_with_appID.lua 

### PR DESCRIPTION
**Pull request by vvvakulenko**
and ATF_GetListOfPermissions_without_appID.lua

### CODE REVIEW

**Comment by vvvakulenko** [comment]
@istoimenova  please review

**Comment by istoimenova** [comment]
@vvvakulenko please check commit, there is no script.

**Comment by istoimenova** [comment]
@vvvakulenko Please add this file to commit with script and close this branch.

**Comment by vvvakulenko** [comment]
review closed due to .json was added to pull request #65

**Pull request closed without merging**
