### PR TITLE
Add scripts to verify 3409 issue

### PR DESCRIPTION
**Pull request by dboltovskyi**
ATF Test Scripts to check [#3409](https://github.com/SmartDeviceLink/sdl_core/issues/3409)

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the issue.

### ATF version
develop

### Changelog
 - New scripts
 - New test set for the issues in scope of `7.1` release

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by jordynmackool** [comment]
@dboltovskyi is this ready for Livio review?

**Comment by dboltovskyi** [comment]
@jordynmackool Yes, this PR is ready for review.

**Review by jacobkeeler — APPROVED** [review]

**Comment by jacobkeeler** [comment]
@dboltovskyi please fix conflicts

**Comment by dboltovskyi** [comment]
@jacobkeeler Please find update in ebb1626

**Pull request merged**
