### PR TITLE
Added files for verifying [Policies]: User consent required on permissions change

### PR DESCRIPTION
**Pull request by aarotar**

### CODE REVIEW

**Comment by aarotar** [comment]
@vvvakulenko please review

**Comment by aarotar** [comment]
@aderiabin, please review

**Comment by aarotar** [comment]
@maria-mih, please review

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge.

**Comment by istoimenova** [comment]
@LuxoftAKutsan please merge.

**Pull request merged**
