### PR TITLE
014 Script for requirement [GeneralResultCodes] INVALID_DATA wrong characters - PerformAudioPassThru

### PR DESCRIPTION
**Pull request by maria-mih**
014_ATF_N_PerformAudioPassThru_INVALID_DATA_Mandatory_Params_audioPassThruIcon_STATIC.lua 
All common functions used available at #703
Testing coverage available at #643
@istoimenova Please review

### CODE REVIEW

**Comment by istoimenova** [comment]
@maria-mih, please update script according to clarification: "Clarification about expected resut code when invalid <audioPassThruIcon> is sent"
@maria-mih, please reference the script in TestSet.

**Comment by maria-mih** [comment]
Script needs to be updated and renamed due to clarification of expected result when invalid parameter received.

**Comment by maria-mih** [comment]
@istoimenova Script is reworked and renamed from 
014_ATF_P_PerformAudioPassThru_WARNINGS_Mandatory_Params_audioPassThruIcon_invalid_whitespaces_STATIC.lua to 
014_ATF_P_PerformAudioPassThru_INVALID_DATA_Mandatory_Params_audioPassThruIcon_whitespaces_STATIC.lua
Please find update at commit 048c261eccee0fbaa02b66ce1fcad8992c40552b

**Comment by maria-mih** [comment]
Script is to be reworked to cover several possible scenarios with different preconditions but one expected result when request sent for mandatory parameters and image type Static and value parameter in image structure is invalid.
It will also be included as negative check of requirement [PerformAudioPassThru] SDL must transfer request to HMI in case of valid "audioPassThruIcon" param

**Comment by maria-mih** [comment]
@istoimenova Please not that script is renamed from 014_ATF_P_PerformAudioPassThru_INVALID_DATA_Mandatory_Params_audioPassThruIcon_whitespaces_STATIC.lua
to 
014_ATF_N_PerformAudioPassThru_INVALID_DATA_Mandatory_Params_audioPassThruIcon_STATIC.lua 
Logic is changed so that all checks for invalid value parameter are included when mandatory parameters of request tested and imagetype = STATIC

**Pull request merged**
