### PR TITLE
Script to check issue 977

### PR DESCRIPTION
**Pull request by HSavynetska**
ATF Test Scripts to check [SDL sends appName in vrSynonyms and ttsName in case of lower and upper bound values of params in json file #977](https://github.com/smartdevicelink/sdl_core/issues/977)

This PR is **not ready** for review.
This is **draft** version of the script. 

### Summary
A test script to verify that issue is fixed

### ATF version
[develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by dboltovskyi** [comment]
Livio team please do not review this PR for now since it hasn't passed our internal review yet.  
Review and appropriate updates going be done till 1st of November.
Thank you.

**Comment by IGapchuk** [comment]
The PR branch has been rebased on the develop branch (https://github.com/smartdevicelink/sdl_atf_test_scripts/commit/457eb480fac0ebcfac7e921f3beefe875ecc36fe).
Script is applicable for all policy flows and transport types.
The script has been moved to Defects/6_2 directory.
Test set for the script is added.

**Comment by dboltovskyi** [comment]
The internal review iteration has been moved to the LuxoftSDL.

**Comment by dboltovskyi** [comment]
The internal review iteration has been moved to the LuxoftSDL.

**Pull request closed without merging**
