### PR TITLE
[SDL 0262] Feature/New vehicle data SeatOccupancy

### PR DESCRIPTION
**Pull request by dboltovskyi**
ATF Test Scripts to check [#3152](https://github.com/smartdevicelink/sdl_core/issues/3152)

This PR is **[ready]** for review.

### Summary
Updates for Vehicle Data scripts related to "[SDL 0262] New vehicle data SeatOccupancy" feature

### ATF version
[7.1.0_version_bump](https://github.com/smartdevicelink/sdl_atf/pull/217)

### Changelog
 - updated common modules for VD and RGNSD tests with new parameters

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@atiwari9 please review this PR

**Comment by atiwari9** [comment]
@dboltovskyi - Can you please rebase with `feature/extended_vd_coverage`

**Comment by dboltovskyi** [comment]
@atiwari9 Please find update in c219e94

**Comment by atiwari9** [comment]
All tests specific to `seatOccupancy` passed: 
[seatOccupancy_AllPass.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/5654321/seatOccupancy_AllPass.zip)

**Review by atiwari9 — APPROVED** [review]
Approved

**Comment by LitvinenkoIra** [comment]
@JackLivio This PR is ready for Livio review. Thank you!

**Comment by jacobkeeler** [comment]
@dboltovskyi please fix conflicts

**Comment by dboltovskyi** [comment]
@jacobkeeler Please find conflicts resolved in 28208a0

**Review by jacobkeeler — APPROVED** [review]

**Pull request merged**
