### PR TITLE
Scripts to check issue 2399

### PR DESCRIPTION
**Pull request by HSavynetska**
ATF Test Scripts to check [#2399](https://github.com/smartdevicelink/sdl_core/issues/2399)

This PR is **not ready** for review.
This is **draft** version of the script.

### Summary
A test scripts to verify that issue is fixed

### ATF version
[develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by dboltovskyi** [comment]
Livio team please do not review this PR for now since it hasn't passed our internal review yet.  
Review and appropriate updates going be done till 1st of November.
Thank you.

**Comment by GetmanetsIrina** [comment]
PR is rebased on actual develop(a7db5cc) branch.
Small update is performed.

**Comment by GetmanetsIrina** [comment]
Script is applicable for all policy flows and transport types.
Script has been moved to 6_1 folder.
Test set for script is added.

**Comment by dboltovskyi** [comment]
The internal review iteration has been moved to the LuxoftSDL.

**Pull request closed without merging**
