### PR TITLE
Added files for verifying [Policies] Treating the device as consented

### PR DESCRIPTION
**Pull request by aarotar**

### CODE REVIEW

**Comment by aarotar** [comment]
@vvvakulenko  please review

**Comment by aarotar** [comment]
@aderiabin please review

**Comment by vvvakulenko** [comment]
@maria-mih Please review

**Comment by aarotar** [comment]
@maria-mih, please review

**Comment by istoimenova** [comment]
@LuxoftAKutsan

**Comment by LuxoftAKutsan** [comment]
@istoimenova merge?

**Comment by istoimenova** [comment]
@LuxoftAKutsan thank you for remark, yes, please merge

**Pull request merged**
