### PR TITLE
[MobileProjection smoke] Fix/failed audio streaming script

### PR DESCRIPTION
**Pull request by IGapchuk**
Fixed issue [# 2164](https://github.com/SmartDeviceLink/sdl_atf_test_scripts/issues/2164)

This PR is **ready** for review.

### Summary
Before checking Audio Service Status, we need stop streaming and add delay.
Because in these scripts ATF isn't really streaming, it is simulation, and sometimes ATF can't get it in time before starting checking Audio Service Status.

### ATF version
[develop](https://github.com/smartdevicelink/sdl_atf/tree/develop)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by dboltovskyi** [comment]
@IGapchuk, @aderiabin Please fix `./test_scripts/MobileProjection/Phase2/smoke/005_audioStreamingState_111-118.lua` in the same way.

**Comment by LuxoftAKutsan** [comment]
@JackLivio @jacobkeeler Can you please look at this fix.  
It is minor changes, but it affects stability of testing Mobile Projection feature.

**Comment by jacobkeeler** [comment]
@IGapchuk The issue states that this is related to `./test_scripts/MobileProjection/Phase2/006_videoStreamingState_001-006.lua` as well, shouldn't this fix be applied there?

**Comment by jacobkeeler** [comment]
Also, neither of these tests fail on my end, are they inconsistent failures?

**Comment by dboltovskyi** [comment]
@jacobkeeler Yes, these are failed accidentally. It could be caught if a single script will be run 10-20 times in a row.

**Comment by dboltovskyi** [comment]
@jacobkeeler 
> The issue states that this is related to ./test_scripts/MobileProjection/Phase2/006_videoStreamingState_001-006.lua as well, shouldn't this fix be applied there?

In this particular script there is no streaming, so fix doesn't needed

**Pull request merged**
