### PR TITLE
023 Script for requirement [PerformAudioPassThru] SDL must transfer reque…

### PR DESCRIPTION
**Pull request by maria-mih**
…st to HMI in case audioPassThruIcon param was omited in request from mobile app

023_ATF_P_PerformAudioPassThru_WARNINGS_All_Params_audioPassThruIcon_invalid_TabChar_DYNAMIC.lua

All common functions used available at #703
@istoimenova Please review

### CODE REVIEW

**Comment by istoimenova** [comment]
@maria-mih, please update script according to clarification: "Clarification about expected resut code when invalid <audioPassThruIcon> is sent"
@maria-mih, please reference the script in TestSet.

**Comment by maria-mih** [comment]
Script needs to be updated and renamed due to clarification of expected result when invalid parameter received.

**Comment by maria-mih** [comment]
Pull request closed as script check already covered in #856

**Comment by maria-mih** [comment]
Pull request closed as script check already covered in #856

**Pull request closed without merging**
