### PR TITLE
Script for issue 967

### PR DESCRIPTION
**Pull request by GetmanetsIrina**
ATF Test Scripts to check #[967](https://github.com/smartdevicelink/sdl_core/issues/967)

This PR is **ready** for review.

### Summary
ATF test script to verify the issue.

### ATF version
[develop](https://github.com/smartdevicelink/sdl_atf/commit/6ed5c5c7a55fa05b015de3db7c04e13b91ace01a)

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by KrupenichOleg** [comment]
Script was updated ([c60d084](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1921/commits/c60d0846a406c6b6f377197e52b4cbe257f53d39)):
1) using PTU instead of changing preloaded_pt file
2) using actions.lua instead of commonDefects.lua

**Comment by KrupenichOleg** [comment]
Script was updated ([8c09c8c](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1921/commits/8c09c8c7d826f2786cd0bae1965f4aa960de1c80)):
1) removed PTU steps and functions (no more needed, preloaded_pt contains OnButtonEvent by default)

**Comment by KrupenichOleg** [comment]
Script updated ([01df3fe](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1921/commits/01df3fee52e353ed0d2ae0c16a351ba49d1865f9)):
1) remove preloaded_pt changing (no more needed, preloaded_pt contains OnButtonEvent by default)
2) use _actions.lua_ instead of _commonDefects.lua_

**Comment by TMyza** [comment]
Rebased to the latest develop(54a1c539ab06d54eda2581ee15d6798ca5b63b49)

**Pull request merged**
