### PR TITLE
Feature/aligning hmi mobile api for pcm stream capabilities

### PR DESCRIPTION
**Pull request by GetmanetsIrina**
ATF Test Scripts to check #[3078](https://github.com/smartdevicelink/sdl_core/issues/3078)

This PR is **not ready** for review.

### Summary
Script for checking pcmStreamCapabilities parameter

### ATF version
develop

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by atiwari9** [comment]
@GetmanetsIrina  - Can you please add another test case to iterate over valid values for: `samplingRate` and `bitsPerSample`

**Comment by aderiabin** [comment]
> @GetmanetsIrina - Can you please add another test case to iterate over valid values for: `samplingRate` and `bitsPerSample`

@atiwari9 First script was updated to check all possible valid combinations of `pcmStreamCapabilities` parameter as you proposed.

**Comment by atiwari9** [comment]
Test Report for atf scripts: [7e16b0b](https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2384/commits/7e16b0b9a6616075652590b96c97eac68b20bf25)

```
=====================================================================================================
TOTAL: 3
PASSED: 3 
FAILED: 0 
ABORTED: 0 
SKIPPED: 0 
=====================================================================================================
```

Logs: 
[Test_report_7e16b0b.zip](https://github.com/smartdevicelink/sdl_atf_test_scripts/files/4819363/Test_report_7e16b0b.zip)

**Comment by LitvinenkoIra** [comment]
@theresalech This PR is ready for review. Thank you.

**Pull request merged**
